### ISSUE TITLE
Rebuild OJS and launch it in production

### ISSUE THREAD

**Issue by bess** [pulibrary/openpublishing#29]
Report via Yuan on slack: Neither of our OJS instances is up at the moment.

- [ ] ~Get them running again in time for Yuan's meeting with a faculty member tomorrow~

Our current plan is to put all of the OJS setup into ansible. 

- [x] Ask Francis what our plan is for when there is a security problem in PHP. Will this plan allow us to rebuild quickly? 

Yes, but we should practice this.

We've asked Yuan to reschedule her meeting because we won't be able to meet this deadline. New acceptance criteria:

- [x] ojs staging and production are running again
- [ ] both systems have monitoring in place
- [x] both systems are built via ansible and the build process is well documented
- [x] Let Yuan know when service has been restored

Added acceptance criteria:
- [ ] ~Yuan's work on the Journal of Japanese Pedagogy has been restored to a working server~
We tried and discovered it isn't supported to back up a journal in one version of the software and restore it to a different version. Yuan understands this and will re-create her sample journal on the newly built systems.

**Comment by bess** [comment]
@kayiwa and I have been trying to diagnose this problem. The error is a "Permission denied" error, and it appears to have been going on for some time. We've tried re-running and ansible playbook, and part of the issue seems to be that the setup on these boxes wasn't done 100% with ansible, so it is under-documented.

**Comment by bess** [comment]
Thanks to some intervention from Trey, we have production back up and running, but we still don't know why it went down in the first place. We should not only fix these but rebuild them and make sure they are monitored, and that we have a robust backup and restore system in place.
